### ISSUE TITLE
45?

### ISSUE THREAD

**Issue by kriskuiper** [MartijnKeesmaat/functional-programming#23]
45 is super arbitrair... misschien kan je me uitleggen waarom 45? En als 'because reasons' dan zou ik 'm opslaan in `mySuperSpecificVariableNameReasonFor45` ofzo.

https://github.com/MartijnKeesmaat/functional-programming/blob/155807dbe3f34b2010f373bfc06e441443c3b541/src/scripts/renderBarChart.js#L74

**Comment by MartijnKeesmaat** [comment]
https://www.independent.co.uk/life-style/history/42-the-answer-to-life-the-universe-and-everything-2205734.html

**Comment by MartijnKeesmaat** [comment]
Fixed it somewhere, I think
